from __future__ import annotations

from .dependency_boundary import (
    FORBIDDEN_CORE_DEPENDENCIES,
    MLDependencyBoundaryError,
    MLDependencyStatus,
    ML_EXTRA_NAME,
    ML_OPTIONAL_DEPENDENCIES,
    detect_ml_dependency_status,
    find_forbidden_core_dependencies,
    normalize_dependency_name,
    require_ml_dependencies,
)
from .default_heuristics import (
    CapabilityMatchupHeuristic,
    GreedyCandidateRanker,
    IdentityPlaybookSelector,
    default_heuristic_registry,
)
from .interfaces import (
    ArtifactResolver,
    BundleSource,
    CandidateRanker,
    MatchupEvaluator,
    PlaybookSelector,
    PolicyBundleHandle,
    PolicyBundleLoader,
)
from .policy_bundle import (
    ArtifactManifestReference,
    JSONPolicyBundleLoader,
    ManifestArtifactResolver,
    ResolvedComponent,
    ResolvedPolicyBundle,
)
from .registry import (
    ArtifactManifest,
    ArtifactManifestStore,
    ComponentResolverRecord,
    HeuristicRegistry,
    PolicyBundleManifest,
    PolicyBundleResolutionError,
    RegistryValidationError,
    ScopeSpec,
    UnknownArtifactError,
    UnknownHeuristicError,
)

__all__ = [
    "ArtifactManifest",
    "ArtifactManifestReference",
    "ArtifactManifestStore",
    "ArtifactResolver",
    "BundleSource",
    "CapabilityMatchupHeuristic",
    "CandidateRanker",
    "ComponentResolverRecord",
    "FORBIDDEN_CORE_DEPENDENCIES",
    "GreedyCandidateRanker",
    "HeuristicRegistry",
    "IdentityPlaybookSelector",
    "JSONPolicyBundleLoader",
    "MLDependencyBoundaryError",
    "MLDependencyStatus",
    "ML_EXTRA_NAME",
    "ML_OPTIONAL_DEPENDENCIES",
    "ManifestArtifactResolver",
    "MatchupEvaluator",
    "PlaybookSelector",
    "PolicyBundleHandle",
    "PolicyBundleLoader",
    "PolicyBundleManifest",
    "PolicyBundleResolutionError",
    "RegistryValidationError",
    "ResolvedComponent",
    "ResolvedPolicyBundle",
    "ScopeSpec",
    "UnknownArtifactError",
    "UnknownHeuristicError",
    "default_heuristic_registry",
    "detect_ml_dependency_status",
    "find_forbidden_core_dependencies",
    "normalize_dependency_name",
    "require_ml_dependencies",
]
