"""Network protocol helpers (message schemas + validation)."""

from .messages import (
    PROTOCOL_VERSION,
    CommandMessage,
    ErrorMessage,
    EventMessage,
    ResyncMessage,
    SnapshotMessage,
    parse_message,
)
from .protocol import EventStreamCursor, build_resync_message, build_snapshot_message, handle_command_message
from .control import build_control_message, parse_control_message
from .lobby import (
    ArmyState,
    LobbyActionResult,
    LobbyState,
    PLAYER_SLOTS,
    ROLE_SPECTATOR,
    apply_army_state,
    apply_auth,
    apply_hello,
    apply_ready,
    apply_role_select,
    disconnect_connection,
    is_ready_to_start,
    mark_started,
    new_lobby_state,
    register_connection,
)
from .client import NetworkClient
from .server import NetworkServer
from .transport import (
    CONTROL_MESSAGE_TYPES,
    GAME_MESSAGE_TYPES,
    ConnectionEvent,
    TransportClient,
    TransportEvent,
    TransportServer,
    build_client_ssl_context,
    build_server_ssl_context,
    decode_message,
    encode_message,
    validate_message,
)

__all__ = [
    "PROTOCOL_VERSION",
    "CommandMessage",
    "ErrorMessage",
    "EventMessage",
    "ResyncMessage",
    "SnapshotMessage",
    "parse_message",
    "EventStreamCursor",
    "build_resync_message",
    "build_snapshot_message",
    "handle_command_message",
    "build_control_message",
    "parse_control_message",
    "ArmyState",
    "LobbyActionResult",
    "LobbyState",
    "PLAYER_SLOTS",
    "ROLE_SPECTATOR",
    "apply_army_state",
    "apply_auth",
    "apply_hello",
    "apply_ready",
    "apply_role_select",
    "disconnect_connection",
    "is_ready_to_start",
    "mark_started",
    "new_lobby_state",
    "register_connection",
    "NetworkClient",
    "NetworkServer",
    "CONTROL_MESSAGE_TYPES",
    "GAME_MESSAGE_TYPES",
    "ConnectionEvent",
    "TransportClient",
    "TransportEvent",
    "TransportServer",
    "build_client_ssl_context",
    "build_server_ssl_context",
    "decode_message",
    "encode_message",
    "validate_message",
]
