"""Pathing package."""

from .dynamic_overlay import (
    DynamicModelBlocker,
    DynamicOverlay,
    build_dynamic_overlay,
    query_enemy_blockers,
    query_enemy_engagement_masks,
    query_friendly_blockers,
)
from .cache import (
    StaticMeshCache,
    StaticMeshCacheEntry,
    StaticMeshCacheKey,
    build_static_mesh_cache_key,
    clear_static_mesh_cache,
    clearance_bucket_for_radius,
    get_static_mesh_cache,
)
from .cdt_mesh import (
    SurfaceCdtMesh,
    SurfacePortal,
    build_surface_cdt_mesh,
    locate_triangles_for_point,
    portal_by_id,
    triangulate_surface_free_space,
)
from .corridor import (
    CorridorResult,
    build_corridor,
    portal_id_between_triangles,
    portal_ids_for_triangle_path,
    string_pull_portals,
)
from .rules_profile import build_movement_profile
from .se2_refine import (
    Se2Pose,
    Se2RefineRequest,
    Se2RefineResult,
    Se2RefineTrigger,
    evaluate_se2_refine_trigger,
    refine_corridor_se2,
)
from .surface_graph import (
    SurfaceConnector,
    SurfaceGraphPathResult,
    SurfaceGraphStatic,
    build_surface_connectors,
    build_surface_free_space,
    build_surface_graph_for_query,
    build_surface_graph_static,
    plan_surface_graph_path,
)
from .surfaces import (
    ELEVATED_LAYER_KIND,
    GROUND_LAYER_KIND,
    GROUND_SURFACE_ID,
    RUINS_LAYER_KIND,
    SupportSurface,
    SupportValidationResult,
    extract_ground_transit_obstacles,
    extract_support_surfaces,
    resolve_support_surface_at_position,
    terrain_ignored_for_ground_transit,
    validate_pose_support,
    validate_pose_support_on_surface,
)
from .types import ConnectorId, MovementProfile, SurfaceId
from .world_snapshot import (
    WorldSnapshot,
    build_world_snapshot,
    movement_profile_signature,
    support_surface_revision,
    terrain_revision,
)

__all__ = [
    "ConnectorId",
    "DynamicModelBlocker",
    "DynamicOverlay",
    "CorridorResult",
    "ELEVATED_LAYER_KIND",
    "GROUND_LAYER_KIND",
    "GROUND_SURFACE_ID",
    "MovementProfile",
    "RUINS_LAYER_KIND",
    "Se2Pose",
    "Se2RefineRequest",
    "Se2RefineResult",
    "Se2RefineTrigger",
    "StaticMeshCache",
    "StaticMeshCacheEntry",
    "StaticMeshCacheKey",
    "SurfaceCdtMesh",
    "SurfaceConnector",
    "SurfaceGraphPathResult",
    "SurfaceGraphStatic",
    "SurfacePortal",
    "SupportSurface",
    "SupportValidationResult",
    "SurfaceId",
    "WorldSnapshot",
    "build_corridor",
    "build_dynamic_overlay",
    "build_movement_profile",
    "build_static_mesh_cache_key",
    "build_surface_cdt_mesh",
    "build_surface_connectors",
    "build_surface_free_space",
    "build_surface_graph_for_query",
    "build_surface_graph_static",
    "build_world_snapshot",
    "clear_static_mesh_cache",
    "clearance_bucket_for_radius",
    "extract_ground_transit_obstacles",
    "extract_support_surfaces",
    "get_static_mesh_cache",
    "locate_triangles_for_point",
    "movement_profile_signature",
    "plan_surface_graph_path",
    "portal_by_id",
    "portal_id_between_triangles",
    "portal_ids_for_triangle_path",
    "query_enemy_blockers",
    "query_enemy_engagement_masks",
    "query_friendly_blockers",
    "resolve_support_surface_at_position",
    "refine_corridor_se2",
    "support_surface_revision",
    "terrain_ignored_for_ground_transit",
    "terrain_revision",
    "triangulate_surface_free_space",
    "evaluate_se2_refine_trigger",
    "validate_pose_support",
    "validate_pose_support_on_surface",
    "string_pull_portals",
]
